### ISSUE TITLE
Can you safely play online in custom games with this (assuming easy anti-cheat is disabled?)

### ISSUE THREAD

**Issue by lukeman3000** [Daylonz/MCCBounceEnable#2]
Pretty much what the title says; would love to do some custom bounce lobbies with friends but don't want to risk ban...

Also, is there any way that I could make SURE the game **always** launches with easy anti-cheat disabled when using this? I'm talking about more out-of-the-box solutions. For example, I was thinking about potentially using an AutoHotkey script to launch MCC with EAC disabled then running this program (if there's a way to launch MCC without EAC via command line or whatever).

**Comment by Daylonz** [comment]
As long as you're playing with the anticheat disabled, you should be just fine to play in private lobbies with friends.
